/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";

export default function PmndrsVan(props: any) {
  const { nodes, materials } = useGLTF("/pmndrsVan.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={3.5} position={[10, 5, 0]}>
        <group position={[0, 0.2, -0.1]}> 
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_body as THREE.Mesh).geometry}
            material={materials.plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_body_1 as THREE.Mesh).geometry}
            material={materials.paintBlue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_body_2 as THREE.Mesh).geometry}
            material={materials.lightFront}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_body_3 as THREE.Mesh).geometry}
            material={materials._defaultMat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_body_4 as THREE.Mesh).geometry}
            material={materials.lightBack}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_body_5 as THREE.Mesh).geometry}
            material={materials.window}
          />     
        </group>
        <group position={[-0.35, 0.3, 0.76]} scale={[-1, 1, 1]}>      
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft as THREE.Mesh).geometry}
            material={materials.carTire}
          />      
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft_1 as THREE.Mesh).geometry}
            material={materials._defaultMat}
          />    
        </group>
        <group position={[0.35, 0.3, 0.76]}>      
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft as THREE.Mesh).geometry}
            material={materials.carTire}
          />   
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft_1 as THREE.Mesh).geometry}
            material={materials._defaultMat}
          />
        </group>
        <group position={[-0.35, 0.3, -0.76]} scale={[-1, 1, 1]}>  
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft as THREE.Mesh).geometry}
            material={materials.carTire}
          /> 
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft_1 as THREE.Mesh).geometry}
            material={materials._defaultMat}
          /> 
        </group>
        <group position={[0.35, 0.3, -0.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft as THREE.Mesh).geometry}
            material={materials.carTire}
          />  
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Mesh_wheel_frontLeft_1 as THREE.Mesh).geometry}
            material={materials._defaultMat}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pmndrsVan.gltf");
